### ISSUE TITLE
Animation drifts slightly when slicing sprite sheets

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#10]
Even on sprite sheets with even pixel dimensions and uniform frame size, there are some artifacts from improper frame alignment.

In the animation shown below, a few pixels from Randall's stomach wrap around the frame near the middle of the animation, even though the source image is pixel-perfect.

![image](https://user-images.githubusercontent.com/22649301/65483490-62fa9600-de6a-11e9-9bca-c8e6fdaa2c08.png)

**Comment by natesampo** [comment]
Resolved the rounding error causing this
