### ISSUE TITLE
Small error in Final Destination platform scaling/position

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#11]
The image for the Final Destination platform is slightly off-center and scaled too large; shown below is the apparent hit box of the platform superimposed on the graphic.

![image](https://user-images.githubusercontent.com/22649301/65483787-75c19a80-de6b-11e9-9bc2-08e9f4961cee.png)

**Comment by natesampo** [comment]
![image](https://user-images.githubusercontent.com/22483011/65820790-3ee8dd00-e1fb-11e9-8bf4-9a711c93a42b.png)
![image](https://user-images.githubusercontent.com/22483011/65820798-5b851500-e1fb-11e9-9d6b-505ede2e05e1.png)

Resolved scaling and positioning of stage background
