### ISSUE TITLE
Falling hitboxes are based on first hitbox in the frame

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#5]
When testing collisions with the stage, only the #1 hitbox in each frame is checked. This causes certain characters to float above the stage, rather than landing and walking.

**Comment by natesampo** [comment]
![image](https://user-images.githubusercontent.com/22483011/72629160-c0d15300-391d-11ea-8cec-cb71e74d1166.png)
Characters whose first hitboxes are not at their feet now walk along the ground as intended.
