### ISSUE TITLE
Images are not uploaded with the "upload fighter" button

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#6]
The "upload fighter" button uploads hitboxes and hurtboxes, but does not apply them to the sprite images provided in the uploaded folder. Additionally, strange artifacts occur that compress certain animations into fewer frames.

![image](https://user-images.githubusercontent.com/22649301/65482752-0b5b2b00-de68-11e9-9a80-6e65164d7146.png)

**Comment by natesampo** [comment]
Resolved both issues here. Upload fighter now loads hitboxes, hurtboxes, and images.

Additionally, it detects the correct number of frames for each of the spritesheets to avoid the compression of entire spritesheets into single frames.
