### ISSUE TITLE
Character sprites are scaled based on the currently selected character

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#7]
Character scaling in the menu changes depending on the currently selected fighter.

For instance, a lower-resolution character like Pong Paddle scales up the other fighters. A larger fighter like Vinny or Randall displays them closer to normal resolution.

![image](https://user-images.githubusercontent.com/22649301/65482848-54ab7a80-de68-11e9-9f7c-b31a8604f314.png)

![image](https://user-images.githubusercontent.com/22649301/65482859-5ecd7900-de68-11e9-8119-689a4fa7f1f3.png)

**Comment by natesampo** [comment]
![image](https://user-images.githubusercontent.com/22483011/72629439-5240c500-391e-11ea-87ea-428de9f2eab2.png)
Characters are now intended size in the selection scene.
