### ISSUE TITLE
"Facing" attribute on "Set Velocity" effect is directional for add mode only

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#8]
When adding a Set Velocity X effect to an attack, the effect is directional with the "facing" option for add mode but not set mode. 

For instance, a horizontal dash correctly increases speed moving left and right when set to "add," but reverses the direction when moving left while in "set" mode, even while "facing" is checked.

![image](https://user-images.githubusercontent.com/22649301/65483220-6b060600-de69-11e9-80dd-6a1c6ce3e66d.png)

**Comment by natesampo** [comment]
Resolved this issue. Unintended behavior caused by a bug from Ludum Dare code.
