### ISSUE TITLE
Unable to remove first attack effect

### ISSUE THREAD

**Issue by jeremycryan** [natesampo/LD43#9]
Upon loading a fighter, the first damage effect cannot be removed from the character.

![image](https://user-images.githubusercontent.com/22649301/65483310-b5878280-de69-11e9-9a2c-2df275aaa7a8.png)

**Comment by natesampo** [comment]
![image](https://user-images.githubusercontent.com/22483011/72630165-c760ca00-391f-11ea-958a-bb2c36961436.png)
The Remove button is now enabled when there is only one attack.
